services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB= Tunez
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "7432:5432"
    volumes:
      -  Tunez_postgres_data:/var/lib/postgresql/data


volumes:
  Tunez_postgres_data: